name: build
on:
  - push
  - pull_request

jobs:
  build:
    name: check and test
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
      - uses: actions/checkout@v5
      
      # Build and run tests
      - name: Build with Maven
        run: mvn -B clean verify --file ./RedmayneEDI.Formats.Fortras100/pom.xml
